apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ku-grade-report-beautifier
  labels:
    app: ku
spec:
  template:
    metadata:
      labels:
        app: ku
        tier: web
    spec:
      containers:
      - name: ku-grade-report-beautifier
        image: gcr.io/steady-hallway-190201/ku-grade-report-beautifier:v1
        ports:
        - containerPort: 8080
